unbind r
bind r source-file ~/.tmux.conf

bind -n S-Right next-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Unbind default and previous prefix keys
unbind C-b

# Set Ctrl-Space as the new prefix
set -g prefix C-Space
bind C-Space send-prefix

set -g mouse on

set-window-option -g mode-keys vi

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g status-position top

# Base status bar styling
set -g status-bg colour235      # Jellybeans dark bg
set -g status-fg colour244      # Light grey text
set -g message-style bg=colour235,fg=colour244

# Left and right status content
set -g status-left-length 20
set -g status-right-length 60
set -g status-left "#[fg=colour117,bg=colour235] #S "  # Cyan for session name
set -g status-right "#[fg=colour214,bg=colour235]%Y-%m-%d #[fg=colour244]%H:%M "

# Window status styling
setw -g window-status-current-style fg=colour235,bg=colour117
setw -g window-status-current-format " #[bold]#I:#W "
setw -g window-status-style fg=colour244,bg=colour235
setw -g window-status-format " #I:#W "

# Pane border styling
set -g pane-border-style fg=colour237
set -g pane-active-border-style fg=colour117

# Mode styling (e.g. copy mode)
set -g mode-style bg=colour235,fg=colour117

# set -g @catppuccin_flavour 'mocha'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'

run '~/.tmux/plugins/tpm/tpm'

# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Window switching keybinds (Alt + Number)
# -n means the keybinding is not prefixed
bind-key -n M-0 select-window -t 0
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9
# Keybind for creating a new window (Alt + t)
bind-key -n M-t new-window


bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

